on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
        otp:
          - version: "24.0.1"
            hash: "test"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.otp.version }}
      - run: echo ${{ matrix.otp.hash }}
