on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
        from-image:
          - name: "windows"
            tag: "20H2"
        otp:
          - version: "24.0.4"
            hash: "A69E439C7C6266B523CBDF66036CEA4597BE477E6914498551C9FBC54FE5770F"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          .\build.ps1 `
            -from_image_name ${{ matrix.from-image.name }} `
            -from_image_tag ${{ matrix.from-image.tag }} `
            -otp_version ${{ matrix.otp.version }} `
            -otp_hash ${{ matrix.otp.hash }}
